Pv/tooling
stac-utils/pystac-client pull request #183
Opened 2022-05-26 17:37 UTC by philvarner

**Related Issue(s):** #

**Description:**

**PR Checklist:**

- [ ] Code is formatted
- [ ] Tests pass
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac-api-client/blob/main/CHANGELOG.md)

2022-05-27 15:06 UTC, philvarner commented
@gadomski @matthewhanson this is ready for review now

2022-05-31 14:43 UTC, gadomski requested changes
One minor script change requested. I did my best to look through the `.py` diffs, but I'll be honest I didn't scan them all -- I assume that there were no functional changes, that the diff noise was from applying the formatters.

2022-05-31 14:43 UTC, gadomski commented on scripts/lint
> +        pre-commit run isort --all-files
IMO `isort` should live in `format` only, not `lint`, so it only gets called once by `scripts/test`.

2022-05-31 14:56 UTC, gadomski approved these changes

2022-05-31 15:24 UTC, merged