Restore default max_items behavior
stac-utils/pystac-client pull request #273
Opened 2022-07-25 21:44 UTC by TomAugspurger

xref https://github.com/stac-utils/pystac-client/issues/237#issuecomment-1179321148

Doesn't close that issue, which also discusses the replacement for the
deprecated methods. This just reverts the change to the default
`max_items` to return all matching items by default.

2022-07-25 21:45 UTC, TomAugspurger commented on pystac_client/item_search.py
> -        max_items: Optional[int] = DEFAULT_LIMIT_AND_MAX_ITEMS,
This `DEFAULT_LIMIT_AND_MAX_ITEMS` is now a misnomer, since it only applies to limit, but it's technically in the public API so I didn't rename it.

2022-07-26 01:29 UTC, TomAugspurger commented on pystac_client/item_search.py
> -        max_items: Optional[int] = DEFAULT_LIMIT_AND_MAX_ITEMS,
(just resolving because of that status check)

2022-08-01 16:15 UTC, gadomski approved these changes
I'm ok w/ this as a MINOR change to incorporate it in a v0.4.1 release. @TomAugspurger do you have a definitive document(s) that describe what constitutes MAJOR, MINOR, and PATCH changes in Python APIs, ala https://doc.rust-lang.org/cargo/reference/semver.html?

2022-08-01 16:20 UTC, gadomski requested changes

2022-08-01 16:22 UTC, TomAugspurger commented
There's no general versioning guidelines in Python. It's up to the project to document its versioning policy, and how that relates to deprecations and compatability

- NumPy's: https://numpy.org/doc/stable/user/depending_on_numpy.html#understanding-numpy-s-versioning-and-api-abi-stability
- pandas': https://pandas.pydata.org/docs/development/policies.html

2022-08-01 16:26 UTC, gadomski approved these changes

2022-08-01 21:29 UTC, merged