Release v0.5.0
stac-utils/pystac-client pull request #303
Opened 2022-08-19 19:15 UTC by gadomski

**Description:**

Release v0.5.0. Not all issues in the v0.5.0 milestone have been closed, but the API refactors and deprecations from #284 are significant enough (IMO) to warrant their own MAJOR release (we're still in v0.y.z, so MAJOR releases bump the second number). If approved, we should move all remaining tickets in https://github.com/stac-utils/pystac-client/milestone/5 to https://github.com/stac-utils/pystac-client/milestone/8.

**PR Checklist:**

- [x] Code is formatted
- [x] Tests pass
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac-api-client/blob/main/CHANGELOG.md)

2022-08-22 14:24 UTC, gadomski commented
Converting to draft because I need to update the front page of the docs to include this new v0.5.0 version.

2022-08-27 12:26 UTC, gadomski commented
Ok updated the table, ready for review.

2022-08-27 13:21 UTC, TomAugspurger approved these changes

2022-08-30 17:56 UTC, gadomski commented on CHANGELOG.md
>  - Search parameter `intersects` is now typed to only accept a str, dict, or object that implements `__geo_interface__` [#169](https://github.com/stac-utils/pystac-client/pull/169)
Good catch, thanks. Fixed.

2022-08-30 18:08 UTC, matthewhanson requested changes

2022-08-30 18:09 UTC, matthewhanson commented on CHANGELOG.md
>  - Client parameter `require_geojson_link` has been removed. [#169](https://github.com/stac-utils/pystac-client/pull/169)
comment on wrong line - PR for `require_geojson_link` should be PR #165

2022-08-30 18:14 UTC, gadomski commented on CHANGELOG.md
>  - Client parameter `require_geojson_link` has been removed. [#169](https://github.com/stac-utils/pystac-client/pull/169)
thanks fixed.

2022-08-30 18:54 UTC, matthewhanson approved these changes

2022-08-30 20:35 UTC, merged